global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Backend (FastAPI) metrics
  - job_name: 'autox-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

