apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        # Extract thread_id from logs and create a link
        - datasourceUid: loki
          matcherRegex: "thread_id: ([a-f0-9-]+)"
          name: thread_id
          url: "$${__value.raw}"

