name: AutoX CD Pipeline

on:
  push:
    branches:
      - main
      - 'dev/*'

jobs:
  backend-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: meta
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME="${{ github.ref_name }}"
            echo "tag=dev-${BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./x_automation_app/backend
          file: ./x_automation_app/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/autox-backend:${{ steps.meta.outputs.tag }}

  frontend-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: meta
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME="${{ github.ref_name }}"
            echo "tag=dev-${BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./x_automation_app/frontend
          file: ./x_automation_app/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/autox-frontend:${{ steps.meta.outputs.tag }}
